In [5]:
import numpy as np
from matplotlib import pyplot as pl
arr1 = np.array([1,2,3,4])
print(arr1)


[1 2 3 4]


TypeError: data type not understood

In [6]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
for i in range(5):
    print(i)

0
1
2
3
4
